name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cached install
      uses: bahmutov/npm-install@v1.1.0
    - name: Test
      run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cached install
      uses: bahmutov/npm-install@v1.1.0
    - name: Build
      run: yarn build
    - name: Upload Build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  release:
    runs-on: ubuntu-latest
    needs:
    - test
    - build
    steps:
    - name: Download Build
      uses: actions/download-artifact@v1
      with:
        name: build
        path: build
    - run: |
        echo "TODO: release"
        cat build/manifest.json
